$color = rgba(18, 18, 18, 1)
$inner_color = rgba(18, 18, 18, 0.66)
$outer_color = rgba(230, 142, 13, 1)
$font_color = rgba(190, 190, 190, 1)
$placeholder_color = rgba(190, 190, 190, 0.7)
$check_color = rgba(255, 193, 7, 1)

label {
    monitor =
    text = 󰈷
    font_size = 48
    color = $font_color
    position = 0, -165
    halign = center
    valign = center
}

label {
    monitor =
    text = $FPRINTPROMPT
    font_size = 16
    color = $font_color
    position = 0, -210
    halign = center
    valign = center
}
