background            #121212
foreground            #bebebe

cursor                #eaeaea
selection_background  #515151
selection_foreground  #bebebe

# black
color0  #333333
color8  #8a8a8d

# red
color1  #d35f5f
color9  #b91c1c

# green
color2  #ffc107
color10 #ffc107

# yellow
color3  #b91c1c
color11 #b90a0a

# blue
color4  #e68e0d
color12 #f59e0b

# magenta
color5  #d35f5f
color13 #b91c1c

#cyan
color6  #bebebe
color14 #eaeaea

#white
color7  #bebebe
color15 #ffffff
