# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#111c18"

# Main text color
theme[main_fg]="#c1c497"

# Title color for boxes
theme[title]="#c1c497"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#509475"

# Background color of selected item in processes box.
theme[selected_bg]="#1d2e25"

# Foreground color of selected item in processes box.
theme[selected_fg]="#c1c497"

# Color of inactive/disabled text
theme[inactive_fg]="#53685b"

# Color of text appearing on top of graphs.
theme[graph_text]="#c1c497"

# Background color of the percentage meters.
theme[meter_bg]="#1d2e25"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text.
theme[proc_misc]="#2dd5b7"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#c1c497"
theme[mem_box]="#63b07a"
theme[net_box]="#d2689c"
theme[proc_box]="#509475"

# Box divider line and small boxes line color
theme[div_line]="#23372b"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#63b07a"
theme[temp_mid]="#e5c736"
theme[temp_end]="#ff5345"

# CPU graph colors (Teal -> Jade -> Pink)
theme[cpu_start]="#2dd5b7"
theme[cpu_mid]="#509475"
theme[cpu_end]="#d2689c"

# Mem/Disk free meter
theme[free_start]="#c1c497"
theme[free_mid]="#509475"
theme[free_end]="#2dd5b7"

# Mem/Disk cached meter
theme[cached_start]="#509475"
theme[cached_mid]="#2dd5b7"
theme[cached_end]="#c1c497"

# Mem/Disk available meter
theme[available_start]="#c1c497"
theme[available_mid]="#acd4cf"
theme[available_end]="#d2689c"

# Mem/Disk used meter (Green -> Teal -> Jade)
theme[used_start]="#63b07a"
theme[used_mid]="#2dd5b7"
theme[used_end]="#509475"

# Download graph colors
theme[download_start]="#c1c497"
theme[download_mid]="#acd4cf"
theme[download_end]="#d2689c"

# Upload graph colors (Green -> Teal -> Jade)
theme[upload_start]="#63b07a"
theme[upload_mid]="#2dd5b7"
theme[upload_end]="#509475"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#2dd5b7"
theme[process_mid]="#509475"
theme[process_end]="#d2689c"
