background            #111c18
foreground            #c1c497

cursor                #d7c995
selection_background  #2c4536
selection_foreground  #c1c497

# black
color0  #23372b
color8  #53685b

# red
color1  #ff5345
color9  #db9f9c

# green
color2  #549e6a
color10 #63b07a

# yellow
color3  #459451
color11 #e5c736

# blue
color4  #509475
color12 #acd4cf

# magenta
color5  #d2689c
color13 #75bbb3

#cyan
color6  #2dd5b7
color14 #8cd3cb

#white
color7  #f6f5dd
color15 #9eebb3
