$color = rgba(45, 53, 59, 1)
$inner_color = rgba(45, 53, 59, 0.66)
$outer_color = rgba(127, 187, 179, 1)
$font_color = rgba(211, 198, 170, 1)
$placeholder_color = rgba(211, 198, 170, 0.7)
$check_color = rgba(131, 192, 146, 1)

label {
    monitor =
    text = 󰈷
    font_size = 48
    color = $font_color
    position = 0, -165
    halign = center
    valign = center
}

label {
    monitor =
    text = $FPRINTPROMPT
    font_size = 16
    color = $font_color
    position = 0, -210
    halign = center
    valign = center
}
